# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:0.60.1

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - hugo
  - cp static/photo-gallery/public static/photo-gallery/pub
  artifacts:
    paths:
    - public
    - static
  only:
  - master

