pages:
# this image is slimmer than official one; based on Alpine
image: fundor333/hugo 
script:
    - hugo
# send all files from public directory to the CI server
artifacts:
    paths:
      - public
only:
    - master  # this job will affect only the 'master' branch
