contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
baseurl       = "https://jumpinglangur.gitlab.io/hugo"
title         = "Toni Sagrista Selles, Personal page and portfolio"
canonifyurls  = true
theme         = "Lanyon"

[indexes]
  category  = "categories"
