contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
baseurl       = "https://jumpinglangur.gitlab.io"
title         = "Toni Sagristà Sellés"
canonifyurls  = true
theme         = "Lanyon"

[indexes]
  category  = "categories"

