baseurl = "https://tonisagrista.com"
languageCode = "en-gb"
title = "Langur Monkey - Toni Sagristà Sellés"
theme = "langurmonkey"
preserveTaxonomyNames = true
enableRobotsTXT = true
canonifyURLs = true
relativeurls = true
uglyurls = false

[pagination]
    pagerSize = 6

[outputs]
    home = ["HTML", "RSS", "JSON"]

[taxonomies]
    tag = "tags"
    category = "categories"

[services.RSS]
    limit = 15


[params]
    # Sets the meta tag description, usually reserved for the main page
    description          = "Personal website and portfolio"
    # This will appear on the top left of the navigation bar
    navbarTitle          = "langur@monkey"
    # Social media buttons that appear in the footer
    socialAppearAtBottom = true
    # Sets where 'View more posts' links
    viewMorePostLink     = "/blog"

    # Optional Params
    categoriesByCount    = true
    tagsByCount          = true
    includeReadingTime   = true
    # Please see the favicon partial template for more information
    loadFavicon          = true
    faviconVersion       = ""

    # Load custom CSS or JavaScript files. This replaces the deprecated params
    # minifiedFilesCSS and minifiedFilesJS. The variable is an array so that you
    # can load multiple files if necessary. You can also load the standard theme
    # files by adding the value, "default".
    customcss              = ["/css/site-bundle.css"]
    customjs               = ["/js/site-bundle.js"]

# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text

[[menu.main]]
    name = "~/blog"
    url = "/blog"
    weight = 2

[[menu.main]]
    name = "~/projects"
    url = "/projects"
    weight = 3

[[menu.main]]
    name = "~/publications"
    url = "/papers"
    weight = 4

[[menu.main]]
    name = "~/cv"
    url = "/resume"
    weight = 5

[[menu.main]]
    name = "~/photo"
    url = "/photography"
    weight = 6

[[menu.main]]
    name = "~/search"
    url = "/search"
    weight = 7


# These go in the footer
[social]
    rss             = "index.xml"
    codeberg        = "langurmonkey"
    #gitlab          = "langurmonkey"
    mastodon        = "@jumpinglangur@mastodon.social"
    mastodont       = "@jumpinglangur@mastodont.cat"
    pixelfed        = "@jumpinglangur"
    lbry            = "@GaiaSky"
    email           = "me@tonisagrista.com"
    pgp             = "0x2FD2A59C1D734C1F"

[markup]
  # code highlight with chroma
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4
  # Properties of the markdown render engine (goldmark)
  [markup.goldmark]
    [markup.goldmark.tableOfContents]
      endLevel = 3
      ordered = false
      startLevel = 2
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
