name = "Langurmonkey"
license = "CC-BY-SA-NC"
licenselink = "https://creativecommons.org/licenses/by-nc-sa/4.0/"
description = "My custom theme, based on Future Imperfect by jpescador"
homepage = "https://gitlab.com/langurmonkey/langurmonkey.gitlab.io"
tags = ["blog", "responsive", "highlight.js", "lunr.js", "light", "dark"]
features = ["html5", "css3", "responsive"]
min_version = 0.15

[author]
  name = "Toni Sagrista"
  homepage = "https://tonisagrista.com"

# If porting an existing theme
[original]
  name = "Future Imperfect"
  homepage = "https://github.com/jpescador/hugo-future-imperfect"
  repo = ""
